import { useEffect, useMemo, useState, type ReactNode } from "react";
import seed from "@/assets/cacao-seed.png";
import { AsuMark, CadburyMark, ChangingFuturesMark } from "@/components/rooted/logos";

const M="#8C1D40", G="#FFC627", C="#F7F0DF", I="#241A20";
const H='"Neue Haas Grotesk Display Pro","Helvetica Neue",Arial,sans-serif';
const B='"Bodoni 72","Bodoni MT",Didot,Georgia,serif';
const E='"EB Garamond",Georgia,serif';
const KEY=(id:string)=>`rooted:planted:${id}`;
const stories=[
  ["EDUCATION","Accelerate","Real college courses come into high schools, helping students earn credit, build confidence and believe they belong in higher education."],
  ["LIFELONG LEARNING","ASU for Life","Personalized learning helps people build skills, networks and confidence as they grow and pivot throughout their careers."],
  ["INNOVATION","CareerCatalyst","Fast, flexible learning helps people upskill and reskill for the future of work through courses and credentials."],
  ["COMMUNITY","Health Literacy","Accessible, community-informed learning helps people navigate care, prevention and informed decisions for themselves and their families."],
] as const;

export function LocalTreeExperience({guestId}:{guestId:string}){
 const id=useMemo(()=>guestId,[guestId]); const [screen,setScreen]=useState(0); const [planted,setPlanted]=useState(false); const [local,setLocal]=useState(0);
 useEffect(()=>{try{if(localStorage.getItem(KEY(id))){setPlanted(true);setScreen(4)}}catch{}},[id]);
 const plant=()=>{if(!planted){try{localStorage.setItem(KEY(id),new Date().toISOString())}catch{} setPlanted(true);setLocal(1)}setScreen(1)};
 return <main className="min-h-screen" style={{background:I,fontFamily:E}}><div className="mx-auto min-h-screen max-w-[520px] overflow-hidden shadow-2xl">{screen===0&&<Invite go={plant}/>} {screen===1&&<SeedReveal go={()=>setScreen(2)}/>} {screen===2&&<Impact local={local} go={()=>setScreen(3)}/>} {screen===3&&<Stories go={()=>setScreen(4)}/>} {screen===4&&<Landscape go={()=>setScreen(5)}/>} {screen===5&&<End/>}</div></main>;
}
function Shell({children,dark=false}:{children:ReactNode;dark?:boolean}){return <section className="relative flex min-h-screen flex-col overflow-hidden px-7 py-8 sm:px-10" style={{background:dark?M:C,color:dark?C:I}}><div className="relative z-10 flex min-h-screen flex-col">{children}</div></section>}
function Header(){return <header className="flex items-center justify-between" style={{fontFamily:H}}><AsuMark/><span className="text-[9px] font-bold uppercase tracking-[.24em]" style={{color:M}}>Changing Futures</span></header>}
function Btn({children,go,dark=false}:{children:ReactNode;go:()=>void;dark?:boolean}){return <button type="button" onClick={go} className="group flex w-full items-center justify-between rounded-full px-5 py-4 text-[12px] font-bold uppercase tracking-[.17em] transition hover:-translate-y-0.5" style={{background:dark?G:M,color:dark?M:C,fontFamily:H}}><span>{children}</span><b className="text-xl">→</b></button>}
function Invite({go}:{go:()=>void}){return <Shell><Header/><div className="mt-16 flex flex-1 flex-col"><p className="text-[10px] font-bold uppercase tracking-[.34em]" style={{fontFamily:H,color:M}}>ASU CHANGING FUTURES</p><h1 className="mt-5 text-[clamp(3.8rem,17vw,6.6rem)] font-bold leading-[.82] tracking-[-.05em]" style={{fontFamily:B,color:M}}>CHANGE<br/>STARTS<br/>WITH A<br/><span style={{color:I}}>SEED.</span></h1><p className="mt-8 max-w-[25rem] border-l-2 pl-5 text-[21px] italic leading-[1.2]" style={{borderColor:G}}>A single seed can become something greater when it is given the opportunity to take root.</p><div className="mt-auto pt-14"><div className="mb-8 flex items-center justify-between"><p className="text-[10px] font-bold uppercase tracking-[.28em]" style={{fontFamily:H}}>Seed / Root / Connect / Flourish</p><img src={seed} alt="Seed" className="h-14 w-14 object-contain"/></div><Btn go={go}>Tap to plant your seed</Btn></div></div></Shell>}
function SeedReveal({go}:{go:()=>void}){const [s,setS]=useState(0);useEffect(()=>{const t=[700,1800,3000,4400,5600].map((d,i)=>setTimeout(()=>setS(i+1),d));return()=>t.forEach(clearTimeout)},[]);return <Shell dark><Header/><div className="flex flex-1 flex-col items-center justify-center text-center"><p className="text-[10px] font-bold uppercase tracking-[.32em]" style={{fontFamily:H,color:G}}>01 / THE SEED</p><div className="relative mt-8 h-[330px] w-full overflow-hidden rounded-[2rem]" style={{background:"linear-gradient(#8C1D40 0 52%,#B99F70 52% 100%)"}}><div className="absolute bottom-[8%] left-1/2 h-24 w-56 -translate-x-1/2 rounded-[50%]" style={{background:"#62422d",opacity:.35}}/><img src={seed} alt="Palo Verde seed" className="absolute left-1/2 z-10 w-20 object-contain" style={{bottom:s?"43%":"57%",transform:`translateX(-50%) scale(${s?".75":"1.05"})`,opacity:s?1:0,transition:"all 900ms ease"}}/><div className="absolute bottom-[19%] left-1/2 h-24 w-24 -translate-x-1/2" style={{opacity:s>=2?1:0,transition:"opacity 800ms ease"}}><i className="absolute left-1/2 h-24 w-px -rotate-12 bg-[#F7F0DF]"/><i className="absolute left-1/2 top-8 h-14 w-px -rotate-[55deg] bg-[#F7F0DF]"/><i className="absolute left-1/2 top-10 h-14 w-px rotate-[55deg] bg-[#F7F0DF]"/></div><div className="absolute bottom-[31%] left-1/2 h-20 w-px -translate-x-1/2" style={{background:G,opacity:s>=3?1:0,transform:`translateX(-50%) scaleY(${s>=4?1:.3})`,transformOrigin:"bottom",transition:"all 800ms ease"}}/><div className="absolute left-1/2 top-[18%] flex -translate-x-1/2 gap-1" style={{opacity:s>=5?1:0,transition:"opacity 700ms ease"}}>{[1,2,3,4,5].map(n=><i key={n} className="h-4 w-4 rounded-full" style={{background:n%2?G:C}}/>)}</div></div><h2 className="mt-8 whitespace-pre-line text-5xl font-bold leading-[.9]" style={{fontFamily:B,color:G}}>{s<2?"YOUR SEED.":s<4?"ROOTS BEGIN\nTO FORM.":"A POSSIBILITY\nTAKES ROOT."}</h2><p className="mt-3 text-lg italic opacity-80">{s<5?"Watch closely.":"Your seed joins thousands of others."}</p>{s>=5&&<div className="mt-7 w-full"><Btn go={go} dark>Continue</Btn></div>}</div></Shell>}
function Impact({local,go}:{local:number;go:()=>void}){const count=12846+local;return <Shell><Header/><div className="flex flex-1 flex-col justify-center"><p className="text-[10px] font-bold uppercase tracking-[.32em]" style={{fontFamily:H,color:M}}>02 / COLLECTIVE IMPACT</p><p className="mt-8 text-[clamp(5rem,25vw,9rem)] font-bold leading-none tracking-[-.06em]" style={{fontFamily:B,color:M}}>{count.toLocaleString()}</p><h2 className="text-3xl font-bold uppercase" style={{fontFamily:H}}>seeds planted</h2><p className="mt-6 text-xl italic">You just added one.</p><p className="mt-8 text-[20px] leading-[1.2]">Every seed represents a person, an idea, an opportunity, or a connection with the potential to create change.</p><p className="mt-6 text-sm opacity-65">Changing Futures is ASU’s bold campaign to shape a future that doesn’t yet exist—but must. It advances learning that unlocks opportunity, supports economic mobility and helps communities thrive.</p><div className="mt-auto pt-8"><Btn go={go}>See what your seed is part of</Btn></div></div></Shell>}
function Stories({go}:{go:()=>void}){const [a,setA]=useState(0);const x=stories[a];return <Shell dark><Header/><div className="flex flex-1 flex-col"><p className="mt-14 text-[10px] font-bold uppercase tracking-[.32em]" style={{fontFamily:H,color:G}}>03 / STORIES</p><h2 className="mt-5 text-6xl font-bold leading-[.88]" style={{fontFamily:B}}>ONE SEED.<br/>MANY STORIES.</h2><p className="mt-5 text-lg italic opacity-80">The seed isn't really about a tree. It is about people, ideas and opportunities that can change what comes next.</p><div className="mt-7 flex gap-2 overflow-x-auto pb-2">{stories.map((v,i)=><button key={v[1]} type="button" onClick={()=>setA(i)} className="shrink-0 rounded-full border px-4 py-2 text-[10px] font-bold tracking-[.16em]" style={{fontFamily:H,borderColor:i===a?G:`${C}55`,background:i===a?G:"transparent",color:i===a?M:C}}>{v[0]}</button>)}</div><article className="mt-6 flex flex-1 flex-col rounded-[2rem] p-6" style={{background:C,color:I}}><span className="text-[10px] font-bold tracking-[.2em]" style={{fontFamily:H,color:M}}>{x[0]}</span><h3 className="mt-auto text-6xl font-bold leading-[.85]" style={{fontFamily:B,color:M}}>{x[1]}</h3><p className="mt-5 text-[21px] leading-[1.15]">{x[2]}</p></article><div className="pt-5"><Btn go={go} dark>See the landscape</Btn></div></div></Shell>}
function Landscape({go}:{go:()=>void}){const dots=Array.from({length:44},(_,i)=>({x:(i*37)%98,y:12+((i*19)%55),d:(i%7)*120}));return <Shell dark><Header/><div className="flex flex-1 flex-col justify-center"><p className="text-[10px] font-bold uppercase tracking-[.32em]" style={{fontFamily:H,color:G}}>04 / THE LANDSCAPE</p><h2 className="mt-5 text-6xl font-bold leading-[.86]" style={{fontFamily:B}}>TOGETHER,<br/>WE'RE<br/><span style={{color:G}}>CHANGING</span><br/>THE LANDSCAPE.</h2><div className="relative mt-8 h-64 overflow-hidden rounded-[2rem]" style={{background:"linear-gradient(#8C1D40 0 48%,#B99F70 48% 100%)"}}><div className="absolute bottom-0 h-20 w-full" style={{background:"#5B754E",clipPath:"polygon(0 70%,20% 38%,43% 64%,62% 30%,81% 58%,100% 36%,100% 100%,0 100%)"}}/>{dots.map((d,i)=><span key={i} className="absolute h-3 w-3 rounded-full" style={{left:`${d.x}%`,bottom:`${d.y}%`,background:G,animation:`bloom 2.2s ease ${d.d}ms infinite alternate`}}/>)}<span className="absolute bottom-3 left-4 text-[9px] font-bold uppercase tracking-[.2em] text-white/70" style={{fontFamily:H}}>One seed → one blossom → a growing community</span></div><p className="mt-7 text-[22px] italic leading-[1.15]">Your contribution is small on its own. Together, individual contributions can create a landscape of opportunity.</p><div className="mt-auto pt-8"><Btn go={go} dark>Make it part of your future</Btn></div></div><style>{`@keyframes bloom{from{opacity:.35;transform:scale(.7)}to{opacity:1;transform:scale(1.15)}}`}</style></Shell>}
function End(){return <Shell><div className="flex flex-1 flex-col"><div className="flex items-center justify-between"><AsuMark/><ChangingFuturesMark/></div><div className="mt-20"><p className="text-[10px] font-bold uppercase tracking-[.32em]" style={{fontFamily:H,color:M}}>05 / YOUR TAKEAWAY</p><h1 className="mt-6 text-[clamp(4rem,18vw,7rem)] font-bold leading-[.8]" style={{fontFamily:B,color:M}}>YOUR SEED<br/><span style={{color:I}}>IS PLANTED.</span></h1><h2 className="mt-8 text-4xl font-bold uppercase" style={{fontFamily:H}}>Now help it grow.</h2><p className="mt-6 text-[21px] leading-[1.18]">Stay connected to Changing Futures and discover the people, ideas and opportunities shaping what’s next.</p></div><div className="mt-auto pt-12"><a href="https://learning.asu.edu/our-impact/changing-futures/" target="_blank" rel="noreferrer" className="flex w-full items-center justify-between rounded-full px-5 py-4 text-[12px] font-bold uppercase tracking-[.17em]" style={{background:M,color:C,fontFamily:H}}>Explore Changing Futures <span className="text-xl">↗</span></a><div className="mt-5 flex items-center justify-between border-t pt-5" style={{borderColor:`${M}33`}}><CadburyMark/><span className="text-[9px] uppercase tracking-[.2em] opacity-60" style={{fontFamily:H}}>Rooted / Watch Change Take Root</span></div></div></div></Shell>}
